# Generated by Django 2.2.16 on 2022-10-18 22:06

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20221018_2100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='User is not author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='User is not author'),
        ),
    ]
