# Generated by Django 2.2.16 on 2022-10-19 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_auto_20221018_2206'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='User is not author',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('user', 'author')},
        ),
    ]
