# Generated by Django 2.2.16 on 2022-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20221020_1302'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='User is not author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='Подписчик - не автор'),
        ),
    ]
